[2022-04-03 18:45:09,753] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: workflow1.create_table3 scheduled__2022-01-01T22:00:00+00:00 [queued]>
[2022-04-03 18:45:09,764] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: workflow1.create_table3 scheduled__2022-01-01T22:00:00+00:00 [queued]>
[2022-04-03 18:45:09,764] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 18:45:09,764] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-03 18:45:09,764] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-03 18:45:09,775] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_table3> on 2022-01-01 22:00:00+00:00
[2022-04-03 18:45:09,783] {standard_task_runner.py:52} INFO - Started process 62961 to run task
[2022-04-03 18:45:09,795] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'workflow1', 'create_table3', 'scheduled__2022-01-01T22:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/extract_file.py', '--cfg-path', '/var/folders/z6/rr0r2zzn64qd2w2102l7_w3r0000gn/T/tmp1q2d_k1a', '--error-file', '/var/folders/z6/rr0r2zzn64qd2w2102l7_w3r0000gn/T/tmpg3cse4gm']
[2022-04-03 18:45:09,797] {standard_task_runner.py:77} INFO - Job 13: Subtask create_table3
[2022-04-03 18:45:14,833] {logging_mixin.py:109} INFO - Running <TaskInstance: workflow1.create_table3 scheduled__2022-01-01T22:00:00+00:00 [running]> on host Manvis-MacBook-Air.local
[2022-04-03 18:45:19,884] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=workflow1
AIRFLOW_CTX_TASK_ID=create_table3
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T22:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T22:00:00+00:00
[2022-04-03 18:45:19,889] {base.py:70} INFO - Using connection to: id: postgres_db. Host: 127.0.0.1, Port: 5432, Schema: airflow_db, Login: postgres, Password: ***, extra: {}
[2022-04-03 18:45:19,962] {dbapi.py:225} INFO - Running statement: CREATE TABLE IF NOT EXISTS contracts (id bigint primary key,type varchar(255), energy varchar(255),energy varchar(255),usage int,usagenet int,createdat date,startdate date,enddate date,filingdatecancellation date,cancellationreason varchar(255),city varchar(255),status varchar(255),productid int, modificationdate date), parameters: None
[2022-04-03 18:45:19,966] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateColumn: column "energy" specified more than once

[2022-04-03 18:45:19,975] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=workflow1, task_id=create_table3, execution_date=20220101T220000, start_date=20220403T164509, end_date=20220403T164519
[2022-04-03 18:45:19,983] {standard_task_runner.py:89} ERROR - Failed to execute job 13 for task create_table3
Traceback (most recent call last):
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/opt/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateColumn: column "energy" specified more than once

[2022-04-03 18:45:20,032] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-03 18:45:20,049] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
